[package]
name = "fluid_simulation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.6"
rayon = "1.7.0"
sdl2 = "0.35.2"
